# Generated by Django 4.2 on 2025-06-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bannershow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Slideshow Title', max_length=100)),
                ('smalltittle', models.CharField(default='Slideshow Small Title', max_length=100)),
                ('image', models.ImageField(default='slideshows/default_slideshow.png', upload_to='slideshows/')),
                ('description', models.TextField(default='Slideshow Description')),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='logos/default_logo.png', upload_to='logos/')),
            ],
        ),
    ]
