# Generated by Django 4.2 on 2025-06-27 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Instagram', max_length=100)),
                ('description', models.TextField()),
                ('hashtag', models.CharField(default='#Male_Fashion', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('fashion', 'Fashion'), ('tech', 'Tech'), ('sport', 'Sport')], default='fashion', max_length=50)),
                ('image', models.ImageField(upload_to='news_images/')),
                ('date', models.DateField(auto_now_add=True)),
                ('button_text', models.CharField(default='Read More', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='instagram_images/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.instagramsection')),
            ],
        ),
    ]
