# Generated by Django 4.2 on 2025-06-27 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_aboutus_teammember_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('link_list', 'Link List'), ('newsletter', 'Newsletter')], default='link_list', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('widget', models.OneToOneField(limit_choices_to={'widget_type': 'newsletter'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.footerwidget')),
            ],
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.URLField(default='#')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='accounts.footerwidget')),
            ],
        ),
    ]
