# Generated by Django 4.2 on 2025-06-27 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_footerwidget_newslettertext_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('best_seller', 'Best Seller'), ('new_arrival', 'New Arrival'), ('hot_sale', 'Hot Sale')], max_length=20)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('sizes', models.JSONField(default=list)),
                ('colors', models.JSONField(default=list)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('is_main', models.BooleanField(default=False)),
                ('is_video', models.BooleanField(default=False)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.product')),
            ],
        ),
    ]
