# Generated by Django 4.2 on 2025-06-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='bannersProduct/')),
                ('link', models.URLField(blank=True, default='#', null=True)),
                ('position_class', models.CharField(blank=True, help_text='e.g. banner__item--middle', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
