# Generated by Django 4.2 on 2025-06-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_bannerproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qr_image', models.ImageField(upload_to='qr_codes/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
