# Generated by Django 4.2 on 2025-06-29 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_qrpaymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.qrpaymentmethod'),
        ),
    ]
