# Generated by Django 5.2.3 on 2025-07-11 14:54

import ckeditor.fields
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_order_qr_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='content1',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='content2',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='content3',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='bannerproduct',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bannershow',
            name='description',
            field=ckeditor.fields.RichTextField(default='Slideshow Description'),
        ),
        migrations.AlterField(
            model_name='bannershow',
            name='smalltittle',
            field=ckeditor.fields.RichTextField(default='Slideshow Small Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='bannershow',
            name='title',
            field=ckeditor.fields.RichTextField(default='Slideshow Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=ckeditor.fields.RichTextField(verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='instagramsection',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='newslettertext',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='qrpaymentmethod',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='quote',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.cart')),
            ],
        ),
    ]
