"""
Django settings for ECommerceProject project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5_+-z9@&ypt(s8i28k%c#(ai7)^^-3ey537ytt1_7%tcfkv!km'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    # 'django_ckeditor_5',
    'django_filters',
    'ckeditor_uploader',
    'accounts',
    'rest_framework',
    'rest_framework.authtoken',
    


]

# style atboard

JAZZMIN_SETTINGS = {
    "site_title": "E-Commerce Admin",
    "site_header": "E-Commerce Admin By Smos5",
    "welcome_sign": "Welcome to E-Commerce Admin Portal",
    "site_brand": "Smos5 Admin",
    "copyright": "Smos5",
    "search_model": "auth.User",
    "show_sidebar": True,
    "navigation_expanded": True,

    "icons": {
        # Django built-in
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users",

        # Your models from 'accounts' or your app name
        "accounts.Order": "fas fa-receipt",
        "accounts.OrderItem": "fas fa-shopping-cart",
        "accounts.AccessToken": "fas fa-key",
        "accounts.Product": "fas fa-box",
        "accounts.ProductImage": "fas fa-images",
        "accounts.FooterWidget": "fas fa-th-large",
        "accounts.FooterLink": "fas fa-link",
        "accounts.NewsletterText": "fas fa-envelope-open-text",
        "accounts.Logo": "fas fa-image",
        "accounts.Bannershow": "fas fa-ad",
        "accounts.InstagramSection": "fab fa-instagram",
        "accounts.InstagramImage": "fas fa-camera-retro",
        "accounts.LatestNews": "fas fa-newspaper",
        "accounts.AboutUs": "fas fa-info-circle",
        "accounts.Testimonial": "fas fa-comment-dots",
        "accounts.TeamMember": "fas fa-users-cog",
        "accounts.Brand": "fas fa-trademark",
        "accounts.Category": "fas fa-tags",
        "accounts.PriceRange": "fas fa-dollar-sign",
        "accounts.Tag": "fas fa-tag",
        "accounts.QRPaymentMethod": "fas fa-qrcode",
        "accounts.ContactMessage": "fas fa-envelope",
        "accounts.BannerProduct": "fas fa-layer-group",
        "accounts.BlogPost": "fas fa-blog",
        "accounts.Comment": "fas fa-comments",
    }
}



# REST_FRAMEWORK = {
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.IsAuthenticated',
#     ],
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'rest_framework.authentication.SessionAuthentication',
#         'rest_framework.authentication.BasicAuthentication',
#     ],
# }

# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'rest_framework.authentication.TokenAuthentication',
#     ],
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.IsAuthenticated',
#     ],
# }


# REST_FRAMEWORK = {
#     'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
# }




CKEDITOR_UPLOAD_PATH = "uploads/"
# CKEDITOR_CONFIGS = {
#     'default': {

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ECommerceProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ECommerceProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"  


# STATICFILES_DIRS = [
#     BASE_DIR / "static",  # or os.path.join(BASE_DIR, "static") if BASE_DIR is a string
# ]


# Media files (user uploaded content)

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # or SMTP
DEFAULT_FROM_EMAIL = 'web@example.com'
ADMIN_EMAIL = 'admin@example.com'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
